// <auto-generated />
using ABManagerWeb.Infrastructure.Data.ABManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABManagerWeb.Infrastructure.Data.ABManager.Migrations
{
    [DbContext(typeof(ABManagerContext))]
    [Migration("20200330090151_MigrateToRemoteDB")]
    partial class MigrateToRemoteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ABManagerWeb.ApplicationCore.Entities.ManifestInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id", "Path", "Version");

                    b.ToTable("ManifestInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
